/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ProdutoDAO;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.beans.Categoria;
import model.beans.Produto;
import util.Validador;
import view.panels.TelaProdutos;

/**
 *
 * @author Vítor
 */
public class CadastroProduto extends javax.swing.JDialog {

    TelaProdutos telaProduto;
    Produto alterarProduto = null;

    /**
     * Creates new form CadastroProduto
     *
     * @param parent
     * @param telaProduto
     */
    public CadastroProduto(JFrame parent, TelaProdutos telaProduto) {
        super(parent, true);
        initComponents();
        this.telaProduto = telaProduto;
        apenasNumeros(txtQtdProd);
        apenasNumeros(txtPrecProd);
    }

    public CadastroProduto(Produto obj, JFrame parent, TelaProdutos telaProduto) {
        super(parent, true);
        initComponents();
        this.getContentPane().setBackground(new Color(255, 255, 255));

        alterarProduto = obj;

        txtNomeProd.setText(String.valueOf(alterarProduto.getNomeProduto()));
        txtPrecProd.setText(String.valueOf(alterarProduto.getPrecoProduto()));
        txtQtdProd.setText(String.valueOf(alterarProduto.getQtdProduto()));
        cbCatProd.setSelectedItem(alterarProduto.getCategoria().getnomeCategoria());
        this.telaProduto = telaProduto;
        btnSalvar.setText("Editar");
        apenasNumeros(txtQtdProd);
        apenasNumeros(txtPrecProd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQtdProd = new javax.swing.JTextField();
        txtPrecProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbCatProd = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabel1.setText("Nome");

        jLabel2.setText("Quantidade");

        txtPrecProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecProdActionPerformed(evt);
            }
        });

        jLabel3.setText("Preço");

        jLabel4.setText("Categoria");

        cbCatProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camisa", "Calça", "Tênis", "Bermuda", "Meia", "Bola" }));

        btnSalvar.setText("Adicionar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeProd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txtQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecProd, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbCatProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCatProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!validaCampos()) {
            return;
        }
        // Verifica se está inserindo ou alterando
        if (alterarProduto == null) {

            // Resgata os dados inseridos pelo usuário
            String nomeProd = txtNomeProd.getText();
            double precProd = Double.parseDouble(txtPrecProd.getText());
            int qtdProd = Integer.parseInt(txtQtdProd.getText());
            String catProd = cbCatProd.getSelectedItem().toString();
            int idCat = 0;

            // Retornando o ID da categoria
            if (catProd.equalsIgnoreCase("camisa")) {
                idCat = 1;
            } else if (catProd.equalsIgnoreCase("calça")) {
                idCat = 2;
            } else if (catProd.equalsIgnoreCase("tênis")) {
                idCat = 3;
            } else if (catProd.equalsIgnoreCase("bermuda")) {
                idCat = 4;
            } else if (catProd.equalsIgnoreCase("meia")) {
                idCat = 5;
            } else if (catProd.equalsIgnoreCase("bola")) {
                idCat = 6;
            }

            Categoria categoria = new Categoria(idCat, catProd);

            //Passar os dados para o objeto
            Produto novoProduto = new Produto(nomeProd, precProd, qtdProd, categoria);

            // Passando o objeto para o banco
            boolean retorno = ProdutoDAO.salvarProduto(novoProduto);

            if (retorno) {
                JOptionPane.showMessageDialog(rootPane, "Sucesso!");
                telaProduto.atualizarTabela();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Falha!");
            }

        } else {
            // Modo de alteração
            String nomeProd = txtNomeProd.getText();
            double precProd = Double.parseDouble(txtPrecProd.getText());

            if (precProd < 0) {
                JOptionPane.showMessageDialog(rootPane, "Por favor, insira valores positivos.");
            }
            int qtdProd = Integer.parseInt(txtQtdProd.getText());
            String catProd = cbCatProd.getSelectedItem().toString();
            int idCat = 0;

            // Retornando o ID da categoria
            if (catProd.equalsIgnoreCase("camisa")) {
                idCat = 1;
            } else if (catProd.equalsIgnoreCase("calça")) {
                idCat = 2;
            } else if (catProd.equalsIgnoreCase("tênis")) {
                idCat = 3;
            } else if (catProd.equalsIgnoreCase("bermuda")) {
                idCat = 4;
            } else if (catProd.equalsIgnoreCase("meia")) {
                idCat = 5;
            } else if (catProd.equalsIgnoreCase("bola")) {
                idCat = 6;
            }

            alterarProduto.setNomeProduto(nomeProd);
            alterarProduto.setPrecoProduto(precProd);
            alterarProduto.setQtdProduto(qtdProd);
            alterarProduto.setIdCategoria(idCat);

            // Passar o objeto para a DAO
            boolean retorno = ProdutoDAO.alterar(alterarProduto);

            if (retorno) {
                JOptionPane.showMessageDialog(rootPane, "Sucesso!");
                telaProduto.atualizarTabela();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Falha!");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private boolean validaCampos() {
        Validador valida = new Validador();
        txtPrecProd.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GRAY));
        txtNomeProd.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GRAY));
        txtQtdProd.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GRAY));

        try {
            txtNomeProd = (JTextField) valida.validaTextField(txtNomeProd);
            txtPrecProd = (JTextField) valida.validaTextField(txtPrecProd);
            txtQtdProd = (JTextField) valida.validaTextField(txtQtdProd);
            if (txtQtdProd.getText().contains(",")) {
                JOptionPane.showMessageDialog(this, "´Por favor, não inclua , no campo de valor, insira .");
                return false;
            }

            return true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Verifique se os campos estão preenchidos");
            return false;
        }
    }

    private void apenasNumeros(JTextField input) {

        input.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent evt) {
                char c = evt.getKeyChar();
                String value = input.getText();
                int l = value.length();
                if (Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE || c == '.') {
                    if (c == '.' && input.getText().contains(".")) {
                        input.setEditable(false);
                    } else {
                        // Permite editar
                        input.setEditable(true);
                    }
                } else {
                    input.setEditable(false);
                }
            }
        });

    }
    private void txtPrecProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecProdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbCatProd;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtPrecProd;
    private javax.swing.JTextField txtQtdProd;
    // End of variables declaration//GEN-END:variables
}
