package view.panels;

import DAO.VendaDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.beans.*;

/**
 *
 * @author Pichau
 */
public class TelaRelatorioCompra extends JDialog {

    private JFrame parentFrame;
    
    public TelaRelatorioCompra(JFrame parent) {
        super(parent, true);
        this.parentFrame = parent;
        initComponents();
    }

    public TelaRelatorioCompra(JFrame parent,int idVenda) {
        super(parent, true);
         this.parentFrame = parent;
        initComponents();

        atualizarTabelaVendas(idVenda);
        atualizaPrecoTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDtVenda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        fieldTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblDesconto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Cliente:");

        lblNome.setText("kaike");

        jLabel1.setText("CPF:");

        lblCPF.setText("123.123.123-23");

        jLabel2.setText("Data Compra:");

        lblDtVenda.setText("10/04/2005");

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NomeProduto", "Quantidade", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblCompras);

        jLabel4.setText("Total:");

        fieldTotal.setEnabled(false);

        jLabel5.setText("Desconto:");

        lblDesconto.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCPF)
                                    .addComponent(lblDtVenda)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDesconto)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNome)
                    .addComponent(jLabel5)
                    .addComponent(lblDesconto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDtVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    public void atualizarTabelaVendas(int idVenda) {
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ArrayList<VendaDescricao> lstRetorno = VendaDAO.buscarPorVenda(idVenda);
            DefaultTableModel modelo = (DefaultTableModel) tblCompras.getModel();

            modelo.setRowCount(0);

            // Para cada item na lista de retorno, adiciono uma linha à tabela
            for (VendaDescricao item : lstRetorno) {
                modelo.addRow(new String[]{
                    String.valueOf(item.getProduto().getNomeProduto()),
                    String.valueOf(item.getProduto().getQtdProduto()),
                    String.valueOf(item.getVenda().getValorVenda())
                });

                String data = formatoData.format(item.getVenda().getDtVenda());
                lblCPF.setText(item.getVenda().getCliente().getCpfCliente());
                lblNome.setText(item.getVenda().getCliente().getNomeCliente());
                lblDtVenda.setText(data);
                lblDesconto.setText(String.valueOf(item.getVenda().getValorDesconto()));
            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, ex, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizaPrecoTotal() {
        DefaultTableModel cartTableModel = (DefaultTableModel) tblCompras.getModel();
        double precoTotal = 0.0;

        // passando sobre as linhas do modelo de tabela do carrinho
        for (int i = 0; i < cartTableModel.getRowCount(); i++) {
            double precoTotalProduto = Double.parseDouble(cartTableModel.getValueAt(i, 2).toString());
            precoTotal += precoTotalProduto;
        }

        fieldTotal.setText(String.format("%.2f", precoTotal));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblDtVenda;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblCompras;
    // End of variables declaration//GEN-END:variables
}
